name: ci

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  quality-check:
    name: Test, Lint & Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5.0

      - name: Run unit tests
        run: go test -v -race ./...

      - name: Build application
        run: go build -v -o /dev/null ./cmd/server
